update_client
talkbank-io/api-baas-python pull request #1
Opened 2021-08-09 10:50 UTC by smikhalyev

2021-08-09 15:44 UTC, lexasngrv requested changes
Давай changelog добавим в формате как в остальных наших либах

2021-08-09 15:44 UTC, lexasngrv commented on README.md
> +`baseUrl = "https://baas.talkbank.io"
https://baas.talkbank.io/v1 вроде, проверь баас, пжл

2021-08-10 05:17 UTC, smikhalyev commented on README.md
> +`baseUrl = "https://baas.talkbank.io"
там есть словарь эндпоинтов и туда уже включен /api/v1/
но нам нужно для авторизации полный URI с учетом /api/v1/........... если вынесем в baseUrl придется парсить от туда /api/v1 либо руками просто дописывать значение /api/v1 к uri из словаря эндпоинтов

2021-08-11 09:37 UTC, lexasngrv submitted a review, later dismissed

2021-08-18 17:01 UTC, lexasngrv approved these changes

2021-08-19 06:57 UTC, merged